language: csharp
solution: EasyCaching.sln
dist: xenial
sudo: required    
dotnet: 3.0.100
mono: none

services:
  - memcached
  - redis-server

os:
  - linux
  - osx
  
osx_image: xcode9.4

branches:
  only:
    - master
    - dev
 
script:
  - dotnet tool install --global FlubuCore.GlobalTool --version 4.2.7
  - flubu build